version: '2.1'

networks:

    # External network
    rosana:

    # Internal network
    miriam:

services:

    clearwing:
	hostname:
            "clearwing"
        image:
           "firethorn/clearwing:${buildtag:-latest}"
        read_only:
            false
        ports:
            - "80:80"
        networks:
            - miriam
