version: '2.1'

networks:

    # External network
    rosana:

    # Internal network
    miriam:

services:

    clearwing:
        hostname:
            "clearwing"
        image:
           "firethorn/clearwing:${clearwing_buildtag:-latest}"
        read_only:
            false
        ports:
            - 80:80
        volumes:
            - ${properties_dir}/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ${properties_dir}/config.py:/var/www/html/app/config.py
            - ${properties_dir}/firethorn.ini:/var/www/html/app/firethorn.ini
        networks:
            - miriam
