version: '2.1'

networks:

    # External network
    rosana:

    # Internal network
    miriam:

services:

    clearwing:
        hostname:
            "clearwing"
        image:
           "firethorn/clearwing:latest"
        read_only:
            false
        stdin_open:
            true
        tty:
            true
        tmpfs:
            - /run
            - /tmp
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            - miriam

